### ISSUE TITLE
Input field has no selection in dark mode

### ISSUE THREAD

**Issue by IronVeil** [IronVeil/britishWeather#1]
When in light mode, the input box has a black border when focused:
![lightmode](https://user-images.githubusercontent.com/46629504/154140751-c177701e-c746-49eb-9910-fe17807eff66.png)

However, in dark mode, it has no border:
![darkmode](https://user-images.githubusercontent.com/46629504/154140782-29a37602-528e-4dcf-9005-609b3254649d.png)

**Comment by ag961** [comment]
What color would you like the border to be in dark mode?
